apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp
  namespace: default
  labels:
    app:  myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app:  myapp
    spec:
      containers:
      - name:  postgres
        image:  postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres" 
        ports:
        - containerPort:  5432
      - name: custom
        image: sulemahnh/k8s-assignment
        ports:
        - containerPort: 3000